spring.application.name=SpringBot

spring.main.headless=false

automation.keyboard.enabled=true


automation.keyboard.command-delay-ms=20
automation.keyboard.post-switch-delay-ms=200

# AWT
spring.main.headless=false

# Switch to previously active application
automation.keyboard.switch-application=true

# Logging
logging.level.root=INFO
# logging.level.com.achhecode.SpringBot=DEBUG
logging.level.com.achhecode.SpringBot=INFO

# Log file
logging.file.name=logs/springbot.log

# Rolling policy
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=500MB
logging.logback.rollingpolicy.clean-history-on-start=false